#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
# Source0 file verified with key 0x528897B826403ADA
#
Name     : libassuan
Version  : 3.0.1
Release  : 23
URL      : https://gnupg.org/ftp/gcrypt/libassuan/libassuan-3.0.1.tar.bz2
Source0  : https://gnupg.org/ftp/gcrypt/libassuan/libassuan-3.0.1.tar.bz2
Source1  : https://gnupg.org/ftp/gcrypt/libassuan/libassuan-3.0.1.tar.bz2.sig
Source2  : 528897B826403ADA.pkey
Summary  : IPC library for the GnuPG components
Group    : Development/Tools
License  : GPL-3.0 LGPL-2.1
Requires: libassuan-bin = %{version}-%{release}
Requires: libassuan-info = %{version}-%{release}
Requires: libassuan-lib = %{version}-%{release}
Requires: libassuan-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gnupg
BuildRequires : libgpg-error-dev
BuildRequires : libgpg-error-extras
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Libassuan
===========
This is a general purpose IPC library which is for example used
GnuPG, GPGME and some other software.

%package bin
Summary: bin components for the libassuan package.
Group: Binaries
Requires: libassuan-license = %{version}-%{release}

%description bin
bin components for the libassuan package.


%package dev
Summary: dev components for the libassuan package.
Group: Development
Requires: libassuan-lib = %{version}-%{release}
Requires: libassuan-bin = %{version}-%{release}
Provides: libassuan-devel = %{version}-%{release}
Requires: libassuan = %{version}-%{release}

%description dev
dev components for the libassuan package.


%package info
Summary: info components for the libassuan package.
Group: Default

%description info
info components for the libassuan package.


%package lib
Summary: lib components for the libassuan package.
Group: Libraries
Requires: libassuan-license = %{version}-%{release}

%description lib
lib components for the libassuan package.


%package license
Summary: license components for the libassuan package.
Group: Default

%description license
license components for the libassuan package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 528897B826403ADA' gpg.status
%setup -q -n libassuan-3.0.1
cd %{_builddir}/libassuan-3.0.1
pushd ..
cp -a libassuan-3.0.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720048771
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720048771
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libassuan
cp %{_builddir}/libassuan-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libassuan/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/libassuan-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/libassuan/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/libassuan-config

%files dev
%defattr(-,root,root,-)
/usr/include/assuan.h
/usr/lib64/libassuan.so
/usr/lib64/pkgconfig/libassuan.pc
/usr/share/aclocal/*.m4

%files info
%defattr(0644,root,root,0755)
/usr/share/info/assuan.info

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libassuan.so.9.0.1
/usr/lib64/libassuan.so.9
/usr/lib64/libassuan.so.9.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libassuan/842745cb706f8f2126506f544492f7a80dbe29b3
/usr/share/package-licenses/libassuan/9a1929f4700d2407c70b507b3b2aaf6226a9543c
