#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0x528897B826403ADA
#
Name     : libassuan
Version  : 2.5.6
Release  : 22
URL      : https://gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.6.tar.bz2
Source0  : https://gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.6.tar.bz2
Source1  : https://gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.6.tar.bz2.sig
Summary  : IPC library for the GnuPG components
Group    : Development/Tools
License  : GPL-3.0 LGPL-2.1
Requires: libassuan-bin = %{version}-%{release}
Requires: libassuan-info = %{version}-%{release}
Requires: libassuan-lib = %{version}-%{release}
Requires: libassuan-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : libgpg-error-dev
BuildRequires : libgpg-error-extras
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Libassuan
===========
This is a general purpose IPC library which is for example used
GnuPG, GPGME and some other software.

%package bin
Summary: bin components for the libassuan package.
Group: Binaries
Requires: libassuan-license = %{version}-%{release}

%description bin
bin components for the libassuan package.


%package dev
Summary: dev components for the libassuan package.
Group: Development
Requires: libassuan-lib = %{version}-%{release}
Requires: libassuan-bin = %{version}-%{release}
Provides: libassuan-devel = %{version}-%{release}
Requires: libassuan = %{version}-%{release}

%description dev
dev components for the libassuan package.


%package info
Summary: info components for the libassuan package.
Group: Default

%description info
info components for the libassuan package.


%package lib
Summary: lib components for the libassuan package.
Group: Libraries
Requires: libassuan-license = %{version}-%{release}

%description lib
lib components for the libassuan package.


%package license
Summary: license components for the libassuan package.
Group: Default

%description license
license components for the libassuan package.


%prep
%setup -q -n libassuan-2.5.6
cd %{_builddir}/libassuan-2.5.6
pushd ..
cp -a libassuan-2.5.6 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1687270131
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1687270131
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libassuan
cp %{_builddir}/libassuan-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libassuan/842745cb706f8f2126506f544492f7a80dbe29b3 || :
cp %{_builddir}/libassuan-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/libassuan/9a1929f4700d2407c70b507b3b2aaf6226a9543c || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/libassuan-config

%files dev
%defattr(-,root,root,-)
/usr/include/assuan.h
/usr/lib64/libassuan.so
/usr/lib64/pkgconfig/libassuan.pc
/usr/share/aclocal/*.m4

%files info
%defattr(0644,root,root,0755)
/usr/share/info/assuan.info

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libassuan.so.0.8.6
/usr/lib64/libassuan.so.0
/usr/lib64/libassuan.so.0.8.6

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libassuan/842745cb706f8f2126506f544492f7a80dbe29b3
/usr/share/package-licenses/libassuan/9a1929f4700d2407c70b507b3b2aaf6226a9543c
